// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu07cvag6PwiX0DB2mx69QS0dyu70WBds',
    appId: '1:964878502977:web:f039fdd69b8da113fb8ac0',
    messagingSenderId: '964878502977',
    projectId: 'minutesforspine',
    authDomain: 'minutesforspine.firebaseapp.com',
    storageBucket: 'minutesforspine.appspot.com',
    measurementId: 'G-V8BJ7EYRTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwbHrjpW3Juc9drf38zJ52-RSVRSAKFQM',
    appId: '1:964878502977:android:0e52b921488b9c6bfb8ac0',
    messagingSenderId: '964878502977',
    projectId: 'minutesforspine',
    storageBucket: 'minutesforspine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnEC7lCGieW0Dz1_PPiZx7rJg7EahLcPI',
    appId: '1:964878502977:ios:b89ef2b599f09f15fb8ac0',
    messagingSenderId: '964878502977',
    projectId: 'minutesforspine',
    storageBucket: 'minutesforspine.appspot.com',
    androidClientId: '964878502977-q2sjidskoqvqk78p48bn7oopgdlfbi8p.apps.googleusercontent.com',
    iosClientId: '964878502977-6nn8g1232o1mk9h2dv7a211cidfseti5.apps.googleusercontent.com',
    iosBundleId: 'pl.fizjo.fizjo',
  );
}
